# DADOS DE ENTRADA

Thin = 56.3755  # TEMPERATURA DE ENTRADA NO CANAL QUENTE
Tcin = 21.6487  # TEMPERATURA DE ENTRADA NO CANAL FRIO
phin = 1.2266  # PRESSÃO DE ENTRADA NO CANAL QUENTE
pcin = 1.0154  # PRESSÃO DE ENTRADA NO CANAL FRIO
mhtotal = 0.2097  # VAZÃO MÁSSICA NO CANAL QUENTE
mctotal = 0.0026  # VAZÃO MÁSSICA NO CANAL FRIO
